"use client";
import {useEffect,useState} from "react";import {useRouter} from "next/navigation";import {createClient} from "../../lib/supabase";
type Player={id:string;name:string;position:string;age:number|null;rating:number;form:number;market_value:number};
export default function Players(){const s=createClient();const router=useRouter();const [club,setClub]=useState<string|null>(null);const [players,setPlayers]=useState<Player[]>([]);const [msg,setMsg]=useState("");const [form,setForm]=useState({name:"",position:"",age:"",rating:"",market_value:""});
async function load(){const {data:{user}}=await s.auth.getUser();if(!user){router.push("/login");return}const {data:m}=await s.from("club_members").select("club_id").eq("user_id",user.id).limit(1).maybeSingle();if(!m){router.push("/onboarding");return}setClub(m.club_id);const {data,error}=await s.from("players").select("*").eq("club_id",m.club_id).order("created_at",{ascending:false});if(error)setMsg(error.message);else setPlayers((data||[]) as Player[])}
useEffect(()=>{load()},[]);
async function add(e:React.FormEvent){e.preventDefault();if(!club)return;const {error}=await s.from("players").insert({club_id:club,name:form.name,position:form.position,age:form.age?Number(form.age):null,rating:form.rating?Number(form.rating):0,market_value:form.market_value?Number(form.market_value):0});if(error)return setMsg(error.message);setForm({name:"",position:"",age:"",rating:"",market_value:""});setMsg("Oyuncu eklendi.");load()}
async function edit(p:Player){const name=prompt("Oyuncu adı",p.name);if(!name)return;const position=prompt("Pozisyon",p.position);if(!position)return;const age=prompt("Yaş",String(p.age??""));const rating=prompt("Reyting",String(p.rating));const market=prompt("Piyasa değeri",String(p.market_value));const {error}=await s.from("players").update({name,position,age:age?Number(age):null,rating:rating?Number(rating):0,market_value:market?Number(market):0}).eq("id",p.id);if(error)setMsg(error.message);else load()}
async function remove(id:string){if(!confirm("Oyuncu silinsin mi?"))return;const {error}=await s.from("players").delete().eq("id",id);if(error)setMsg(error.message);else load()}
return <main style={{minHeight:"100vh",background:"#080d0b",color:"white",padding:"32px",fontFamily:"Arial"}}><div style={{maxWidth:1100,margin:"auto"}}><button onClick={()=>router.push("/")} style={ghost}>← Dashboard</button><small style={{color:"#49ad60"}}>DISPFICS • CANLI VERİ</small><h1>Oyuncular</h1><div style={{marginTop:24,color:"#aab7af",fontSize:13}}>Yeni oyuncu ekle</div><form onSubmit={add} style={{display:"grid",gridTemplateColumns:"2fr 1fr 1fr 1fr 1fr auto",gap:8,margin:"8px 0 24px"}}><input required placeholder="Oyuncu adı" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} style={input}/><input required placeholder="Pozisyon" value={form.position} onChange={e=>setForm({...form,position:e.target.value})} style={input}/><input type="number" placeholder="Yaş" value={form.age} onChange={e=>setForm({...form,age:e.target.value})} style={input}/><input type="number" step=".1" min="0" max="10" placeholder="Reyting" value={form.rating} onChange={e=>setForm({...form,rating:e.target.value})} style={input}/><input type="number" placeholder="Değer ₺" value={form.market_value} onChange={e=>setForm({...form,market_value:e.target.value})} style={input}/><button style={primary}>Ekle</button></form><p style={{color:"#9bcba7"}}>{msg}</p><div style={{border:"1px solid #203027",borderRadius:14,overflow:"hidden"}}>{players.length===0?<p style={{padding:24,color:"#aab7af"}}>Henüz oyuncu yok. İlk oyuncuyu yukarıdan ekleyin.</p>:players.map(p=><div key={p.id} style={{display:"grid",gridTemplateColumns:"2fr 1fr 1fr 1fr 1fr auto",gap:10,alignItems:"center",padding:"16px",borderBottom:"1px solid #203027"}}><b>{p.name}</b><span>{p.position}</span><span>{p.age??"—"} yaş</span><span>{Number(p.rating).toFixed(1)}</span><span>₺{Number(p.market_value).toLocaleString("tr-TR")}</span><div style={{display:"flex",gap:6}}><button onClick={()=>router.push(`/players/${p.id}`)} style={ghost}>Detay</button><button onClick={()=>edit(p)} style={ghost}>Düzenle</button><button onClick={()=>remove(p.id)} style={ghost}>Sil</button></div></div>)}</div></div></main>}
const input={padding:11,background:"#0e1512",color:"white",WebkitTextFillColor:"white",caretColor:"white",border:"1px solid #294032",borderRadius:8,minWidth:0};const primary={padding:"11px 18px",background:"#2e9d4b",color:"white",border:0,borderRadius:8,fontWeight:700};const ghost={padding:"9px 12px",background:"transparent",color:"#9bcba7",border:"1px solid #294032",borderRadius:8,cursor:"pointer"};
