"use client";
import {useState} from "react";
import {useRouter} from "next/navigation";
import {LayoutDashboard,Users,Search,BrainCircuit,BarChart3,Settings,Shield,TrendingUp,Activity,ArrowUpRight} from "lucide-react";
const players=[["Mert Günok","KL","7.4"],["Semih Kılıçsoy","ST","7.8"],["Gedson Fernandes","MO","7.6"],["Rafa Silva","OS","8.1"],["Emirhan Topçu","STP","7.2"]];
const nav=[["Genel Bakış",LayoutDashboard],["Aktif Kadro",Users],["Oyuncular",Activity],["Transfer Merkezi",Search],["AI Teknik Asistan",BrainCircuit],["Analiz",BarChart3]];
export default function Home(){const [active,setActive]=useState("Genel Bakış");const router=useRouter();function choose(n:string){if(n==="Oyuncular"){router.push("/players");return}setActive(n)}return <main><aside><div className="brand"><div className="mark">D</div><div><b>DISPFICS</b><small>DIGITAL SPORTS ANALYTICS</small></div></div><nav>{nav.map(([n,I]:any)=><button className={active===n?"on":""} onClick={()=>choose(n)} key={n}><I size={18}/>{n}</button>)}</nav><button className="settings"><Settings size={18}/>Ayarlar</button></aside><section><header><div><span className="eyebrow">KULÜP YÖNETİM PANELİ</span><h1>{active}</h1></div><div className="club"><Shield/><div><b>Dispfics FC</b><small>2026/27 Sezonu</small></div></div></header>{active==="Genel Bakış"?<Dashboard/>:<Module title={active}/>}</section></main>}
function Dashboard(){return <><div className="hero"><div><span className="pill">AI ANALİZİ AKTİF</span><h2>Kararlar artık<br/><em>veriye dayanıyor.</em></h2><p>Kadronuzu analiz edin, performansı takip edin ve yapay zekâ destekli önerilerle maçlara hazırlanın.</p><button>AI Analizini Gör <ArrowUpRight size={17}/></button></div><div className="score"><small>TAKIM FORMU</small><strong>8.4</strong><span>↑ %12 son 5 maç</span></div></div><div className="stats"><Card t="Kadro Değeri" v="₺482M" s="+4.2%"/><Card t="Ortalama Reyting" v="7.46" s="+0.31"/><Card t="Formda Oyuncu" v="8" s="Son 5 maç"/><Card t="Kazanma Olasılığı" v="%68" s="Sıradaki maç"/></div><div className="grid"><div className="panel"><div className="panelHead"><div><small>AKTİF KADRO</small><h3>İlk 11 Performansı</h3></div><button>Takımı Yönet</button></div><div className="pitch"><span className="p gk">1</span><span className="p d1">4</span><span className="p d2">5</span><span className="p d3">3</span><span className="p d4">2</span><span className="p m1">6</span><span className="p m2">8</span><span className="p a1">10</span><span className="p a2">7</span><span className="p a3">11</span><span className="p st">9</span></div></div><div className="panel"><small>OYUNCU FORMU</small><h3>Öne Çıkanlar</h3><div className="players">{players.map((p,i)=><div className="player" key={p[0]}><i>{i+1}</i><div><b>{p[0]}</b><small>{p[1]}</small></div><strong>{p[2]}</strong></div>)}</div></div></div></>}
function Card({t,v,s}:{t:string,v:string,s:string}){return <div className="card"><small>{t}</small><strong>{v}</strong><span><TrendingUp size={14}/>{s}</span></div>}
function Module({title}:{title:string}){return <div className="module"><span className="pill">MVP MODÜLÜ</span><h2>{title}</h2><p>Bu modül Dispfics ürün mimarisine hazırlandı. Sonraki iterasyonda gerçek kulüp verisi, Supabase ve AI servisleri bağlanabilir.</p><div className="moduleBox"><BrainCircuit size={48}/><h3>Dispfics Intelligence</h3><p>Futbol kararlarını tek panelde birleştiren veri ve yapay zekâ katmanı.</p></div></div>}