"use client";
import {useEffect,useState} from "react";import {useRouter} from "next/navigation";
import {LayoutDashboard,Users,Search,BrainCircuit,BarChart3,Settings,Shield,TrendingUp,Activity,ArrowUpRight} from "lucide-react";import {createClient} from "../lib/supabase";
const nav=[["Genel Bakış",LayoutDashboard],["Aktif Kadro",Users],["Oyuncular",Activity],["Transfer Merkezi",Search],["AI Teknik Asistan",BrainCircuit],["Analiz",BarChart3]];
export default function Home(){const [active,setActive]=useState("Genel Bakış");const [clubName,setClubName]=useState("");const router=useRouter();useEffect(()=>{(async()=>{const s=createClient();const {data:{user}}=await s.auth.getUser();if(!user)return;const {data:m}=await s.from("club_members").select("club_id").eq("user_id",user.id).order("created_at",{ascending:false}).limit(1).maybeSingle();if(!m)return;const {data:c}=await s.from("clubs").select("name").eq("id",m.club_id).maybeSingle();setClubName(c?.name||"")})()},[]);function choose(n:string){if(n==="Oyuncular"){router.push("/players");return}if(n==="Aktif Kadro"){router.push("/lineup");return}if(n==="Transfer Merkezi"){router.push("/transfers");return}if(n==="AI Teknik Asistan"){router.push("/ai");return}setActive(n)}return <main><aside><div className="brand"><div className="mark">D</div><div><b>DISPFICS</b><small>DİJİTAL SPOR ANALİTİĞİ</small></div></div><nav>{nav.map(([n,I]:any)=><button className={active===n?"on":""} onClick={()=>choose(n)} key={n}><I size={18}/>{n}</button>)}</nav><button className="settings"><Settings size={18}/>Ayarlar</button></aside><section><header><div><span className="eyebrow">KULÜP YÖNETİM PANELİ</span><h1>{active}</h1></div><div className="club"><Shield/><div><b>{clubName||"Dispfics"}</b><small>Canlı kulüp verisi</small></div></div></header>{active==="Genel Bakış"?<Dashboard router={router}/>:<Module title={active}/>}</section></main>}
function Dashboard({router}:any){const [club,setClub]=useState<any>(null);const [players,setPlayers]=useState<any[]>([]);const [metrics,setMetrics]=useState<any[]>([]);const [matches,setMatches]=useState<any[]>([]);const [loading,setLoading]=useState(true);
useEffect(()=>{(async()=>{const s=createClient();const {data:{user}}=await s.auth.getUser();if(!user){router.push("/login");return}const {data:m}=await s.from("club_members").select("club_id").eq("user_id",user.id).order("created_at",{ascending:false}).limit(1).maybeSingle();if(!m){router.push("/onboarding");return}const c=await s.from("clubs").select("*").eq("id",m.club_id).single();const clubName=c.data?.name;const [sp,x,mt]=await Promise.all([s.from("scouting_players").select("id,name,position,overall,estimated_value_eur").eq("is_active",true).eq("club",clubName).order("overall",{ascending:false}),s.from("player_metrics").select("*").eq("club_id",m.club_id).order("match_date",{ascending:false}).limit(100),s.from("matches").select("*").eq("club_id",m.club_id).order("kickoff",{ascending:false}).limit(5)]);setClub(c.data);setPlayers((sp.data||[]).map((p:any)=>({...p,rating:p.overall,market_value:p.estimated_value_eur||0})));setMetrics(x.data||[]);setMatches(mt.data||[]);setLoading(false)})()},[]);
if(loading)return <div className="module"><span className="pill">CANLI VERİ</span><h2>Genel bakış hazırlanıyor…</h2></div>;
const value=players.reduce((a,p)=>a+Number(p.market_value||0),0),avg=players.length?players.reduce((a,p)=>a+Number(p.rating||0),0)/players.length:0;const recent=metrics.slice(0,30);const formPlayers=players.filter(p=>recent.some(m=>m.player_id===p.id&&Number(m.rating)>=7.5)).length;const teamForm=recent.length?recent.reduce((a,m)=>a+Number(m.rating),0)/recent.length:avg;const top=[...players].sort((a,b)=>Number(b.rating)-Number(a.rating)).slice(0,5);
return <><div className="hero"><div><span className="pill">CANLI ANALİZ</span><h2>{club?.name||"Kulübünüz"}<br/><em>veriyle yönetiliyor.</em></h2><p>Oyuncu ve performans kayıtlarınız Supabase üzerinden canlı hesaplanıyor.</p><button onClick={()=>router.push("/players")}>Oyuncuları Yönet <ArrowUpRight size={17}/></button></div><div className="score"><small>TAKIM FORMU</small><strong>{teamForm.toFixed(1)}</strong><span>{recent.length} performans kaydı</span></div></div><div className="stats"><Card t="Kadro Değeri" v={money(value)} s={players.length+" oyuncu"}/><Card t="Ortalama Puan" v={avg.toFixed(2)} s="Canlı kadro"/><Card t="Formda Oyuncu" v={String(formPlayers)} s="7.5+ puan"/><Card t="Son Maçlar" v={String(matches.length)} s="Kayıtlı maç"/></div><div className="grid"><div className="panel"><div className="panelHead"><div><small>PERFORMANS</small><h3>Son Kayıtlar</h3></div><button onClick={()=>router.push("/players")}>Veri Ekle</button></div><div className="players">{recent.slice(0,6).map((m,i)=><div className="player" key={m.id}><i>{i+1}</i><div><b>{m.opponent}</b><small>{m.match_date} • {m.minutes}'</small></div><strong>{Number(m.rating).toFixed(1)}</strong></div>)}{!recent.length&&<p>Henüz performans kaydı yok.</p>}</div></div><div className="panel"><small>OYUNCU FORMU</small><h3>Öne Çıkanlar</h3><div className="players">{top.map((p,i)=><div className="player" key={p.id}><i>{i+1}</i><div><b>{p.name}</b><small>{p.position}</small></div><strong>{Number(p.rating).toFixed(1)}</strong></div>)}{!top.length&&<p>İlk oyuncunuzu ekleyin.</p>}</div></div></div></>}
function money(n:number){if(n>=1e9)return "€"+(n/1e9).toFixed(1)+"B";if(n>=1e6)return "€"+(n/1e6).toFixed(1)+"M";if(n>=1e3)return "€"+(n/1e3).toFixed(0)+"K";return "€"+n.toLocaleString("tr-TR")}
function Card({t,v,s}:{t:string,v:string,s:string}){return <div className="card"><small>{t}</small><strong>{v}</strong><span><TrendingUp size={14}/>{s}</span></div>}
function Module({title}:{title:string}){return <div className="module"><span className="pill">MVP MODÜLÜ</span><h2>{title}</h2><p>Bu modül sonraki ürün iterasyonunda canlı kulüp verisi ve Dispfics Intelligence ile genişletilecek.</p><div className="moduleBox"><BrainCircuit size={48}/><h3>Dispfics Intelligence</h3><p>Futbol kararlarını tek panelde birleştiren veri ve yapay zekâ katmanı.</p></div></div>}
