"use client";
import {useEffect,useState} from "react";import {useParams,useRouter} from "next/navigation";import {createClient} from "../../../lib/supabase";
export default function PlayerDetail(){const {id}=useParams<{id:string}>();const router=useRouter();const s=createClient();const [p,setP]=useState<any>(null);const [rows,setRows]=useState<any[]>([]);const [msg,setMsg]=useState("");const [f,setF]=useState({opponent:"",match_date:"",minutes:"90",goals:"0",assists:"0",rating:""});
async function load(){const {data:player,error}=await s.from("players").select("*").eq("id",id).single();if(error){setMsg(error.message);return}setP(player);const {data}=await s.from("player_metrics").select("*").eq("player_id",id).order("match_date",{ascending:false});setRows(data||[])}
useEffect(()=>{load()},[id]);
async function add(e:React.FormEvent){e.preventDefault();if(!p)return;const {error}=await s.from("player_metrics").insert({player_id:id,club_id:p.club_id,opponent:f.opponent,match_date:f.match_date||new Date().toISOString().slice(0,10),minutes:Number(f.minutes),goals:Number(f.goals),assists:Number(f.assists),rating:Number(f.rating)});if(error)setMsg(error.message);else{setMsg("Performans kaydedildi.");setF({...f,opponent:"",rating:""});load()}}
const avg=rows.length?rows.reduce((a,x)=>a+Number(x.rating),0)/rows.length:0;
return <main style={{minHeight:"100vh",background:"#080d0b",color:"white",padding:32,fontFamily:"Arial"}}><div style={{maxWidth:1000,margin:"auto"}}><button onClick={()=>router.push("/players")} style={ghost}>← Oyuncular</button>{p&&<><small style={{color:"#49ad60"}}>OYUNCU PROFİLİ</small><h1>{p.name}</h1><p style={{color:"#aab7af"}}>{p.position} • {p.age??"—"} yaş • Güncel reyting {Number(p.rating).toFixed(1)}</p><div style={{display:"flex",gap:12,margin:"20px 0"}}><Card t="Maç Kaydı" v={String(rows.length)}/><Card t="Ort. Reyting" v={avg.toFixed(2)}/><Card t="Gol" v={String(rows.reduce((a,x)=>a+x.goals,0))}/><Card t="Asist" v={String(rows.reduce((a,x)=>a+x.assists,0))}/></div><form onSubmit={add} style={{display:"grid",gridTemplateColumns:"2fr 1fr 1fr 1fr 1fr 1fr auto",gap:8,margin:"24px 0"}}>{["opponent","match_date","minutes","goals","assists","rating"].map(k=><input key={k} required={k==="opponent"||k==="rating"} type={k==="match_date"?"date":k==="opponent"?"text":"number"} step={k==="rating"?".1":undefined} placeholder={{opponent:"Rakip",match_date:"Tarih",minutes:"Dakika",goals:"Gol",assists:"Asist",rating:"Reyting"}[k]} value={(f as any)[k]} onChange={e=>setF({...f,[k]:e.target.value})} style={input}/>) }<button style={primary}>Kaydet</button></form><p style={{color:"#9bcba7"}}>{msg}</p><div style={{border:"1px solid #203027",borderRadius:14,overflow:"hidden"}}>{rows.map(x=><div key={x.id} style={{display:"grid",gridTemplateColumns:"1.4fr 1fr repeat(4,.7fr)",padding:14,borderBottom:"1px solid #203027"}}><b>{x.opponent}</b><span>{x.match_date}</span><span>{x.minutes}'</span><span>{x.goals} G</span><span>{x.assists} A</span><strong>{Number(x.rating).toFixed(1)}</strong></div>)}</div></>}</div></main>}
function Card({t,v}:{t:string,v:string}){return <div style={{flex:1,padding:18,background:"#0e1512",border:"1px solid #203027",borderRadius:12}}><small style={{color:"#aab7af"}}>{t}</small><h2>{v}</h2></div>}const input={padding:10,background:"#0e1512",color:"white",border:"1px solid #294032",borderRadius:8,minWidth:0};const primary={padding:"10px 16px",background:"#2e9d4b",color:"white",border:0,borderRadius:8};const ghost={padding:"9px 12px",background:"transparent",color:"#9bcba7",border:"1px solid #294032",borderRadius:8,cursor:"pointer"};
