"use client";
import {useEffect,useState} from "react";import {useRouter} from "next/navigation";import {createClient} from "../../lib/supabase";
import AppShell from "../components/AppShell";
const slots=[["GK","Kaleci"],["LB","Sol Bek"],["LCB","Stoper"],["RCB","Stoper"],["RB","Sağ Bek"],["LDM","Orta Saha"],["RDM","Orta Saha"],["LAM","Sol Kanat"],["CAM","10 Numara"],["RAM","Sağ Kanat"],["ST","Forvet"]];
export default function Lineup(){const s=createClient();const router=useRouter();const [players,setPlayers]=useState<any[]>([]);const [lineup,setLineup]=useState<any>(null);const [selected,setSelected]=useState<Record<string,string>>({});const [msg,setMsg]=useState("");
async function load(){const {data:{user}}=await s.auth.getUser();if(!user)return router.push("/login");const {data:m}=await s.from("club_members").select("club_id").eq("user_id",user.id).limit(1).maybeSingle();if(!m)return router.push("/onboarding");const {data:p}=await s.from("players").select("*").eq("club_id",m.club_id).order("rating",{ascending:false});setPlayers(p||[]);let {data:l}=await s.from("lineups").select("*").eq("club_id",m.club_id).eq("is_active",true).limit(1).maybeSingle();if(!l){const x=await s.from("lineups").insert({club_id:m.club_id,name:"İlk 11",formation:"4-2-3-1"}).select().single();l=x.data}setLineup(l);if(l){const {data:lp}=await s.from("lineup_players").select("*").eq("lineup_id",l.id);const map:Record<string,string>={};(lp||[]).forEach(x=>map[x.slot]=x.player_id);setSelected(map)}}
useEffect(()=>{load()},[]);
async function save(){if(!lineup)return;const vals=Object.entries(selected).filter(([,v])=>v);if(new Set(vals.map(x=>x[1])).size!==vals.length)return setMsg("Aynı oyuncu iki pozisyonda olamaz.");await s.from("lineup_players").delete().eq("lineup_id",lineup.id);if(vals.length){const {error}=await s.from("lineup_players").insert(vals.map(([slot,player_id])=>({lineup_id:lineup.id,slot,player_id})));if(error)return setMsg(error.message)}setMsg("İlk 11 kaydedildi.")}
return <AppShell title="Aktif Kadro"><div style={{maxWidth:1050}}><small style={{color:"#49ad60"}}>İLK 11 • 4-2-3-1</small><p style={{color:"#aab7af"}}>Kulübünüzdeki oyuncuları pozisyonlara atayın ve aktif kadroyu kaydedin.</p><div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:12,margin:"24px 0"}}>{slots.map(([slot,label])=><label key={slot} style={{padding:14,border:"1px solid #203027",borderRadius:12,background:"#0e1512"}}><small style={{color:"#49ad60"}}>{slot} • {label}</small><select value={selected[slot]||""} onChange={e=>setSelected({...selected,[slot]:e.target.value})} style={input}><option value="">Oyuncu seç</option>{players.map(p=><option key={p.id} value={p.id}>{p.name} • {p.position} • {Number(p.rating).toFixed(1)}</option>)}</select></label>)}</div><button onClick={save} style={primary}>İlk 11'i Kaydet</button><span style={{marginLeft:14,color:"#9bcba7"}}>{msg}</span></div></AppShell>}
const input={display:"block",width:"100%",marginTop:9,padding:11,background:"#080d0b",color:"white",border:"1px solid #294032",borderRadius:8};const primary={padding:"12px 20px",background:"#2e9d4b",color:"white",border:0,borderRadius:8,fontWeight:700,cursor:"pointer"};const ghost={padding:"9px 12px",background:"transparent",color:"#9bcba7",border:"1px solid #294032",borderRadius:8,cursor:"pointer"};
