"use client";
import {useEffect,useState} from "react";import {useRouter} from "next/navigation";import {createClient} from "../../lib/supabase";
import AppShell from "../components/AppShell";
export default function AI(){const s=createClient();const router=useRouter();const [context,setContext]=useState<any>(null);const [q,setQ]=useState("");const [busy,setBusy]=useState(false);const [chat,setChat]=useState<{q:string;a:string}[]>([]);
useEffect(()=>{(async()=>{const {data:{user}}=await s.auth.getUser();if(!user)return router.push("/login");const {data:m}=await s.from("club_members").select("club_id").eq("user_id",user.id).limit(1).maybeSingle();if(!m)return router.push("/onboarding");const [club,players,metrics,targets,lineup]=await Promise.all([s.from("clubs").select("id,name").eq("id",m.club_id).single(),s.from("players").select("id,name,position,age,rating,form,market_value").eq("club_id",m.club_id),s.from("player_metrics").select("player_id,match_date,opponent,minutes,goals,assists,rating").eq("club_id",m.club_id).order("match_date",{ascending:false}).limit(60),s.from("transfer_targets").select("name,position,age,current_club,market_value,rating,priority,status").eq("club_id",m.club_id),s.from("lineups").select("id,name,formation").eq("club_id",m.club_id).eq("is_active",true).limit(1).maybeSingle()]);let lp:any[]=[];if(lineup.data){const x=await s.from("lineup_players").select("slot,player_id").eq("lineup_id",lineup.data.id);lp=x.data||[]}setContext({club:club.data,players:players.data||[],recent_performances:metrics.data||[],transfer_targets:targets.data||[],active_lineup:lineup.data?{...lineup.data,players:lp}:null})})()},[]);
async function ask(text?:string){const message=(text||q).trim();if(!message||!context||busy)return;setBusy(true);setQ("");try{const r=await fetch("/api/ai",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message,context})});const d=await r.json();setChat(x=>[...x,{q:message,a:d.reply||d.error||"Yanıt alınamadı."}])}catch{setChat(x=>[...x,{q:message,a:"AI servisine ulaşılamadı."}])}setBusy(false)}
const prompts=["Hangi pozisyona transfer yapmalıyız?","En formda 5 oyuncuyu sırala.","Mevcut kadroya göre ilk 11 öner.","Transfer shortlist'imi değerlendir."];
return <AppShell title="AI Teknik Asistan"><div style={{maxWidth:900}}><small style={{color:"#49ad60"}}>DISPFICS INTELLIGENCE</small><p style={{color:"#aab7af"}}>Asistan yalnızca kulübünüzde kayıtlı kadro, performans, aktif 11 ve transfer verilerini bağlam olarak kullanır.</p><div style={{display:"flex",flexWrap:"wrap",gap:8,margin:"20px 0"}}>{prompts.map(p=><button key={p} onClick={()=>ask(p)} style={ghost}>{p}</button>)}</div><div style={{display:"grid",gap:14,margin:"24px 0"}}>{chat.map((x,i)=><div key={i}><div style={{padding:14,background:"#172019",borderRadius:12,marginBottom:6}}><b>Sen:</b> {x.q}</div><div style={{padding:18,background:"#0e1512",border:"1px solid #203027",borderRadius:12,whiteSpace:"pre-wrap",lineHeight:1.55}}><b style={{color:"#49ad60"}}>Dispfics AI</b><br/>{x.a}</div></div>)}</div><div style={{display:"flex",gap:8,position:"sticky",bottom:18,background:"#080d0b",padding:"12px 0"}}><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")ask()}} placeholder={context?"Kulübün hakkında bir soru sor…":"Kulüp verileri yükleniyor…"} disabled={!context||busy} style={input}/><button onClick={()=>ask()} disabled={!context||busy} style={primary}>{busy?"Analiz ediliyor…":"Sor"}</button></div></div></AppShell>}
const input={flex:1,padding:14,background:"#0e1512",color:"white",border:"1px solid #294032",borderRadius:10};const primary={padding:"12px 22px",background:"#2e9d4b",color:"white",border:0,borderRadius:9,fontWeight:700};const ghost={padding:"9px 12px",background:"transparent",color:"#9bcba7",border:"1px solid #294032",borderRadius:8,cursor:"pointer"};
