"use client";
import {useEffect,useMemo,useState} from "react";import {useRouter} from "next/navigation";import {createClient} from "../../lib/supabase";import AppShell from "../components/AppShell";
type P={external_id:string;club:string|null;league:string|null;overall:number|null;estimated_value_eur:number|null;gender?:{label?:string}|null};
type SortKey="rating"|"value"|"players"|"name";
const PAGE_SIZE=200;
export default function Teams(){const s=createClient(),router=useRouter();const [ps,setPs]=useState<P[]>([]),[q,setQ]=useState(""),[league,setLeague]=useState(""),[gender,setGender]=useState(""),[sort,setSort]=useState<SortKey>("rating"),[direction,setDirection]=useState<"desc"|"asc">("desc"),[loading,setLoading]=useState(true),[msg,setMsg]=useState(""),[page,setPage]=useState(0);
useEffect(()=>{(async()=>{const {data:{user}}=await s.auth.getUser();if(!user){router.replace("/login");return}try{let all:P[]=[];for(let n=0;;n+=1000){const {data,error}=await s.from("scouting_players").select("external_id,club,league,overall,estimated_value_eur,gender").eq("is_active",true).order("external_id").range(n,n+999);if(error)throw error;all=all.concat((data||[]) as P[]);if(!data||data.length<1000)break}setPs(all)}catch(e){setMsg(e instanceof Error?e.message:"Takımlar yüklenemedi.")}setLoading(false)})()},[]);
const teams=useMemo(()=>{const m=new Map<string,any>();for(const p of ps){if(!p.club)continue;const g=p.gender?.label||"—",key=[p.club,p.league||"—",g].join("|");const x=m.get(key)||{name:p.club,league:p.league||"—",gender:g,players:0,rating:0,value:0};x.players++;x.rating+=Number(p.overall||0);x.value+=Number(p.estimated_value_eur||0);m.set(key,x)}return Array.from(m.values()).map(x=>({...x,rating:x.rating/x.players}))},[ps]);
const leagues=useMemo(()=>Array.from(new Set(teams.map(x=>x.league))).filter(x=>x!=="—").sort(),[teams]);const genders=useMemo(()=>Array.from(new Set(teams.map(x=>x.gender))).filter(x=>x!=="—").sort(),[teams]);
const shown=useMemo(()=>teams.filter(x=>(!q||fold(x.name).includes(fold(q)))&&(!gender||x.gender===gender)&&(!league||x.league===league)).sort((a,b)=>{let n=0;if(sort==="name")n=a.name.localeCompare(b.name,"tr");else if(sort==="value")n=a.value-b.value;else if(sort==="players")n=a.players-b.players;else n=a.rating-b.rating;return direction==="asc"?n:-n}),[teams,q,gender,league,sort,direction]);
useEffect(()=>{setPage(0)},[q,gender,league,sort,direction]);
const pageCount=Math.max(1,Math.ceil(shown.length/PAGE_SIZE)),safePage=Math.min(page,pageCount-1),visible=shown.slice(safePage*PAGE_SIZE,(safePage+1)*PAGE_SIZE);
return <AppShell title="Takımlar"><div><div className="teamFilters"><input placeholder="Takım ara" value={q} onChange={e=>setQ(e.target.value)} style={input}/><select value={gender} onChange={e=>setGender(e.target.value)} style={input}><option value="">Tüm Cinsiyetler</option>{genders.map(x=><option key={x}>{x}</option>)}</select><select value={league} onChange={e=>setLeague(e.target.value)} style={input}><option value="">Tüm Ligler</option>{leagues.map(x=><option key={x}>{x}</option>)}</select><select value={sort} onChange={e=>setSort(e.target.value as SortKey)} style={input}><option value="rating">Ort. Dispfics Reyting</option><option value="value">Kadro Değeri</option><option value="players">Oyuncu Sayısı</option><option value="name">Takım Adı</option></select><select value={direction} onChange={e=>setDirection(e.target.value as "desc"|"asc")} style={input}><option value="desc">{sort==="name"?"Z → A":"Azalan"}</option><option value="asc">{sort==="name"?"A → Z":"Artan"}</option></select></div><p style={{color:"#8fa399"}}>{loading?"Takımlar oluşturuluyor…":shown.length.toLocaleString("tr-TR")+" takım"} {msg}</p><div className="teamGrid">{visible.map((x,i)=><button key={x.name+"|"+x.league+"|"+x.gender} className="teamCard" onClick={()=>router.push("/teams/"+encodeURIComponent(x.name)+"?league="+encodeURIComponent(x.league)+"&gender="+encodeURIComponent(x.gender))}><div style={{display:"flex",gap:14,alignItems:"center"}}><b style={{minWidth:34,textAlign:"center"}}><small style={{display:"block",color:"#718078",fontSize:9}}>SIRA</small>{safePage*PAGE_SIZE+i+1}</b><div><small>{x.league}</small><h3>{x.name}</h3><span>{x.gender}</span></div></div><div className="teamMetrics"><b>{x.players}<small>OYUNCU</small></b><b>{x.rating.toFixed(1)}<small>ORT. REYTİNG</small></b><b>{money(x.value)}<small>KADRO DEĞERİ</small></b></div></button>)}</div>{shown.length>PAGE_SIZE&&<div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:12,marginTop:18}}><button disabled={safePage===0} onClick={()=>setPage(p=>Math.max(0,p-1))} style={pager}>Önceki 200</button><span style={{color:"#8fa399"}}>{(safePage*PAGE_SIZE+1).toLocaleString("tr-TR")}–{Math.min((safePage+1)*PAGE_SIZE,shown.length).toLocaleString("tr-TR")} / {shown.length.toLocaleString("tr-TR")}</span><button disabled={safePage>=pageCount-1} onClick={()=>setPage(p=>Math.min(pageCount-1,p+1))} style={pager}>Sonraki 200</button></div>}</div></AppShell>}
function fold(v:string){return v.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/ı/g,"i").replace(/ş/g,"s").replace(/ğ/g,"g").replace(/ü/g,"u").replace(/ö/g,"o").replace(/ç/g,"c")}function money(v:number){return v>=1e6?"€"+(v/1e6).toLocaleString("tr-TR",{maximumFractionDigits:1})+"M":"€"+Math.round(v/1000).toLocaleString("tr-TR")+"K"}const input={padding:12,background:"#0e1512",color:"white",border:"1px solid #294032",borderRadius:9,minWidth:0};const pager={padding:"10px 16px",background:"#0e1512",color:"white",border:"1px solid #294032",borderRadius:9,cursor:"pointer"};
